import {
  Activity,
  BarChart3,
  Bell,
  CheckSquare,
  CreditCard,
  FileText,
  Flag,
  FolderKanban,
  Gauge,
  Globe2,
  Key,
  Receipt,
  Shield,
  Users,
  Zap,
} from "lucide-react";

export const features = [
  {
    icon: Users,
    title: "Client Management",
    desc: "Centralized client records with relationship tracking, projects, files, and invoice history.",
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-500",
  },
  {
    icon: FolderKanban,
    title: "Project Delivery",
    desc: "Plan, track, and ship projects with timelines, teams, attached files, and per-client portals.",
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-500",
  },
  {
    icon: CheckSquare,
    title: "Task Workflows",
    desc: "Kanban boards and list views with status pipelines, assignees, mentions, and due dates.",
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
  },
  {
    icon: CreditCard,
    title: "Stripe Billing",
    desc: "Subscriptions, the customer portal, invoices, refunds, and webhook-driven plan updates.",
    iconBg: "bg-amber-500/10",
    iconColor: "text-amber-500",
  },
  {
    icon: Receipt,
    title: "Invoicing & GST",
    desc: "Manual and Stripe-driven invoices, India GST tax breakdown, and automated dunning reminders.",
    iconBg: "bg-orange-500/10",
    iconColor: "text-orange-500",
  },
  {
    icon: BarChart3,
    title: "Analytics",
    desc: "Per-org and platform-wide rollups for project health, task velocity, and revenue trends.",
    iconBg: "bg-cyan-500/10",
    iconColor: "text-cyan-500",
  },
  {
    icon: Bell,
    title: "Notifications",
    desc: "In-app, email, and web push channels with per-event preferences and unsubscribe support.",
    iconBg: "bg-rose-500/10",
    iconColor: "text-rose-500",
  },
  {
    icon: Shield,
    title: "Security & RBAC",
    desc: "Role-based access, TOTP 2FA, audit logs, IP allowlisting, and rate-limited public endpoints.",
    iconBg: "bg-indigo-500/10",
    iconColor: "text-indigo-500",
  },
  {
    icon: Activity,
    title: "Status & Uptime",
    desc: "Self-hosted public status page with component states, incident history, and email subscribers.",
    iconBg: "bg-green-500/10",
    iconColor: "text-green-500",
  },
  {
    icon: Key,
    title: "API & Webhooks",
    desc: "REST API with org-scoped keys for clients, projects, tasks, and invoices. Stripe webhooks built in.",
    iconBg: "bg-slate-500/10",
    iconColor: "text-slate-500",
  },
  {
    icon: Flag,
    title: "Feature Flags",
    desc: "Two-tier flag system - global defaults plus per-org overrides - controlled from the admin panel.",
    iconBg: "bg-fuchsia-500/10",
    iconColor: "text-fuchsia-500",
  },
  {
    icon: Gauge,
    title: "Platform Admin",
    desc: "Cross-org admin console with audited impersonation, usage views, and operational dashboards.",
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-500",
  },
  {
    icon: FileText,
    title: "Files & Media",
    desc: "Cloudinary-backed uploads with signed URLs, previews, and per-client visibility controls.",
    iconBg: "bg-yellow-500/10",
    iconColor: "text-yellow-500",
  },
  {
    icon: Globe2,
    title: "Client Portals",
    desc: "Public-facing portals for each client with project visibility, file sharing, and invoice access.",
    iconBg: "bg-sky-500/10",
    iconColor: "text-sky-500",
  },
  {
    icon: Zap,
    title: "Multi-Tenant by Design",
    desc: "Strict per-organization data isolation enforced at every server boundary, not just the UI.",
    iconBg: "bg-pink-500/10",
    iconColor: "text-pink-500",
  },
];
