export const plans = [
  {
    code: "starter",
    name: "Starter",
    price: "$29",
    period: "/mo",
    desc: "For small teams getting started",
    features: [
      "5 team members",
      "15 clients",
      "10 projects",
      "15 files per project",
      "100 tasks/month",
      "50 file uploads/month",
      "Basic analytics",
      "Email support",
    ],
    cta: "Start Free Trial",
  },
  {
    code: "professional",
    name: "Professional",
    price: "$79",
    period: "/mo",
    desc: "For growing agencies",
    features: [
      "Unlimited team members",
      "Unlimited clients",
      "Unlimited projects",
      "Unlimited files & uploads",
      "Advanced analytics",
      "Priority support",
      "API access",
      "Custom branding",
    ],
    cta: "Start Free Trial",
    featured: true,
  },
  {
    code: "enterprise",
    name: "Enterprise",
    price: "Custom",
    period: "",
    desc: "For large organizations",
    features: [
      "Unlimited members",
      "Unlimited projects & clients",
      "Unlimited files & tasks",
      "Custom integrations",
      "Dedicated support",
      "SSO/SAML",
      "SLA guarantee",
    ],
    cta: "Contact Sales",
  },
];
